import Head from "next/head";
import Anchor from "@/components/Anchor";

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Her er min shop</h1>
      <section className="products">
        {products.map((product) => (
          <article>
            <h2>{product.productdisplayname}</h2>
            <p>{product.price},-</p>
            <Anchor href={"/products/" + product.id}>Read more</Anchor>
          </article>
        ))}
      </section>
    </>
  );
}
//Laver en html side EN gang (per build) (getStaticProps)
export async function getStaticProps() {
  // Get data from api
  const api = "https://kea-alt-del.dk/t7/api/products?";
  const res = await fetch(api);
  const data = await res.json();
  // Return the data inside props
  return {
    props: {
      products: data,
    },
  };
}

//Laver en ny html side ved hvert besøg (serverSideProps)
/* export async function getServerSideProps() {
  // Get data from api
  const api = "https://kea-alt-del.dk/t7/api/products?";
  const res = await fetch(api);
  const data = await res.json();
  // Return the data inside props
  return {
    props: {
      products: data,
    },
  };
} */
